rootPath: ""

genesis:
  difficulty: "0"
  gasLimit: "16716680"
  coinbase: "0000000000000000000000000000000000000000"
  alloc: {}
  chainId: "1"
  timestamp: 0
  miners: []

log:
  logDir: /dev/null
  level: INFO
  maxLogs: 15

history:
  frontierBlockNumber: "0"
  homesteadBlockNumber: "0"
  tangerineWhistleBlockNumber: "0"
  spuriousDragonBlockNumber: "0"
  byzantiumBlockNumber: "0"
  constantinopleBlockNumber: "1000000000000000000000"

keystore:
  initkey: ""
  dir: ""

peer:
  host: localhost
  port: 30314
  seeds: []
  updatePeersInterval: "10 seconds"
  maxOutgoingPeers: 10
  maxIncomingPeers: 10
  minPeers: 0
  bufferSize: 4194304 # 4 MiB
  timeout: "10 seconds"

sync:
  maxBlockHeadersPerRequest: 128
  maxBlockBodiesPerRequest: 128
  offset: 10
  checkInterval: "5 seconds"
  banDuration: "200 seconds"
  requestTimeout: "10 seconds"

txPool:
  poolSize: 4096
  transactionTimeout: "10 minutes"

blockPool:
  maxBlockAhead: 10
  maxBlockBehind: 10

mining:
  enabled: true
  address: "0x4ab032a020fad1872aae6b036fdcec8a428da570"
  passphrase: "changeit"
  coinbase: "0000000000000000000000000000000000000000"
  period: "100 millis"
  epoch: "30000"
  minBroadcastPeers: 4

persist:
  driver: memory
  path: ""
  columnFamilies:
    - default
    - BlockHeader
    - BlockBody
    - Receipts
    - Snapshot
    - Node
    - Code
    - TotalDifficulty
    - AppState
    - Peer
    - NumberHash
    - TxLocation

ssl:
  enabled: false
  keyStorePath: ""
  trustStorePath: ""
  protocol: "TLS"
  clientAuth: "NotRequested"

db:
  driver: "org.h2.jdbcx.JdbcDataSource"
  url: "jdbc:h2:mem:jbok_test;MODE=MYSQL;DB_CLOSE_DELAY=-1"
  user: "sa"
  password: ""

service:
  enable: true
  enableHttp2: true
  enableWebsockets: false
  secure: false
  logHeaders: true
  logBody: true
  enableMetrics: false
  allowedOrigins: []
  local: localhost
  host: 127.0.0.2
  port: 30315
  apis:
    - account
    - admin
    - block
    - contract
    - miner
    - personal
    - transaction
